services:
  - type: web
    name: mindmirror-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html